blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/arif-banai/MusicBot/discussions/categories/general
    about: For general questions, please check the Discussions
  - name: Troubleshooting
    url: https://github.com/arif-banai/MusicBot/discussions/categories/help
    about: For troubleshooting help, please check the Discussions
