name: Make Release
on:
  workflow_dispatch:
    inputs:
      version_number:
        description: 'Version Number'     
        required: true
        type: string
      info:
        description: 'Description of this Release'
        required: true
        type: string

jobs:
  build_jar:
    name: Build Jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java Environment
        uses: ./.github/actions/setup-java
      - name: Set Version
        run: |
          mvn -B versions:set -DnewVersion=${{ github.event.inputs.version_number }}
          mvn -B versions:commit

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Rename jar
        run: mv target/*-All.jar JMusicBot-${{ github.event.inputs.version_number }}.jar
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: JMusicBot-${{ github.event.inputs.version_number }}.jar
          if-no-files-found: error
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build_jar
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: jar
          path: .
      - name: Show Artifacts
        run: ls -R
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ github.event.inputs.version_number }}
          name: v${{ github.event.inputs.version_number }}
          draft: true
          prerelease: false
          artifacts: "*.jar"
          body: |
            ${{ github.event.inputs.info }}
            
            ---
            ### Setup
            https://jmusicbot.com/setup  
            https://jmusicbot.com/config  
            # Download: [JMusicBot-${{ github.event.inputs.version_number }}.jar](https://github.com/arif-banai/MusicBot/releases/download/v${{ github.event.inputs.version_number }}/JMusicBot-${{ github.event.inputs.version_number }}.jar)
